name: Validate Branches for Pull Request

on:
  pull_request:
    types: opened

jobs:
  validate-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Validate base and head branches
        run: |

          if: ${{ github.event.pull_request.base.ref  == 'staging' && github.event.pull_request.head.ref  != 'main' || github.event.pull_request.base.ref == 'production' && github.event.pull_request.head.ref != 'staging' }} then
            echo "Error: The head branch must be 'main' when the base is 'staging'."
            exit 1
          fi
