name: Exclude from Productivity Metrics

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Apply release label
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ (github.event.pull_request.base.ref == 'staging' && github.event.pull_request.head.ref == 'main') || (github.event.pull_request.base.ref == 'production' && github.event.pull_request.head.ref == 'staging') }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: test
