name: Exclude from Productivity Metrics

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Apply release label
        uses: actions-ecosystem/action-add-labels@v1
        env:
          HEAD_REF: ${{ github.event.pull_request.head.ref }}
          BASE_REF: ${{ github.event.pull_request.base.ref }}
        if: ${{ (env.BASE_REF == 'staging' && env.HEAD_REF == 'main') || (env.BASE_REF == 'production' && env.HEAD_REF == 'staging') }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: test
