name: pr label
on:
  pull_request:
    branches:
      - main
      - staging
      - production

jobs:
  pr-label:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: agaroot-technologies/action-restrict-pr-label@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          rules: |
            staging <- main [test]
            staging <- revert-* [test] 
            main <- staging [test]
            main <- revert-* [test]

            production <- staging [test]
            production <- revert-* [test] 
            staging <- production [test]
            staging <- revert-* [test]
