name: Hello World Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  say_hello:
    runs-on: ubuntu-latest
    # 環境変数の定義はjobレベル
    env: # 環境変数の定義
      BRANCH: main # 「BRANCH」という名前の環境変数へ、「main」という値をセット
      ACTOR: ${{ github.actor }} # コンテキストの値を環境変数へセット
      USERNAME: ${{ vars.USERNAME }} # Variablesの参照
      PASSWORD: ${{ secrets.PASSWORD }} # Secretsの参照
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Print Hello World
        run: echo "Hello World"
      - name: ワークフロー実行者のログ
        run: echo "${{ github.actor }}" # githubコンテキストの参照、これはアンチパターンで「中間環境変数でActorにアクセス」するべき
      - name: プルリクのタイトル
        run: echo "${{ github.event.pull_request.title }}" # github.eventプロパティはオブジェクト型
      - name: 環境変数をecho
        run: echo "${BRANCH}" # シェルコマンドからジョブレベルの環境変数を参照
        env:
          BRANCH: ブランチをオーバーライドしてます
          run: echo "${ env.BRANCH }"
      - name: GITHUB_ACTOR
        run: echo "${GITHUB_ACTOR}"
      - name: github.actor
        run: echo "${{ github.actor }}"
      - name: 中間環境変数でActorにアクセス
        run: echo "${ACTOR}" # 環境変数経由でコンテキストのプロパティを参照
      - name: varableの参照
        run: echo "${USERNAME}"
      - name: secretsの参照 ログ出力はマスクされる
        run: echo "${PASSWORD}" # ログ出力はマスクされる
      - name: secretsの参照 ログ出力はマスクされない
        run: echo "${PASSWORD:0:1} ${PASSWORD#?}" # ログ出力はマスクされない
