name: Hello World Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  say_hello:
    runs-on:
      ubuntu-latest
      # 環境変数の定義はjobレベル
    env: # 環境変数の定義
      BRANCH: main # 「BRANCH」という名前の環境変数へ、「main」という値をセット

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Hello World
        run: echo "Hello World"
      - name: ワークフロー実行者のログ
        run: echo "${{ github.actor }}" # githubコンテキストの参照
      - name: プルリクのタイトル
        run: echo "${{ github.event.pull_request.title }}" # github.eventプロパティはオブジェクト型

      - name: 環境変数をecho
        run: echo "${BRANCH}" # シェルコマンドからジョブレベルの環境変数を参照

      - uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH }} # envコンテキスト経由でジョブレベルの環境変数を参照

        env:
          BRANCH: 変わったよー
          run: echo "${ BRANCH}"
