name: Hello World Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  say_hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Hello World
        run: echo "Hello World"
      - name: ワークフロー実行者のログ
        run: echo "${{ github.actor }}" # githubコンテキストの参照
      - name: プルリクのタイトル
        run: echo "${{ github.event.pull_request.title }}" # github.eventプロパティはオブジェクト型
