name: Validate Release PR

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
      - staging
      - production

jobs:
  validate-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Fail if branch conditions are not met (Condition 1)
        if: ${{ github.event.pull_request.head.ref == 'production' }}
        run: |
          echo "Error: Branch conditions are not met for PR (head is production)."
          exit 1

      - name: Fail if branch conditions are not met (Condition 2)
        if: ${{ github.event.pull_request.head.ref == 'staging' && github.event.pull_request.base.ref != 'production' }}
        run: |
          echo "Error: Branch conditions are not met for PR (staging -> non-production base)."
          exit 1

      - name: Fail if branch conditions are not met (Condition 3)
        if: ${{ github.event.pull_request.base.ref == 'staging' && github.event.pull_request.head.ref != 'main' }}
        run: |
          echo "Error: Branch conditions are not met for PR (staging -> non-main head)."
          exit 1

      - name: Fail if branch conditions are not met (Condition 4)
        if: ${{ github.event.pull_request.base.ref == 'production' && github.event.pull_request.head.ref != 'staging' }}
        run: |
          echo "Error: Branch conditions are not met for PR (production -> non-staging head)."
          exit 1
